namespace: "pulsar-dev"
#
# uncomment these for install:
#
#namespaceCreate: true
initialize: true


# made affinity preferred.
# Note: you need to also set this for each component or else the global value will be overwritten by the default.
affinity:
  anti_affinity: true
  type: requiredDuringSchedulingIgnoredDuringExecution





volumes:
  persistence: true
  local_storage: false


components:
  # zookeeper
  zookeeper: true
  # bookkeeper
  bookkeeper: true
  # bookkeeper - autorecovery
  autorecovery: true
  # broker
  broker: true
  # functions
  functions: false # enabling this with tls is broken. Not sure what it does or if we will need it. TODO
  # proxy
  proxy: true
  # toolset
  toolset: true
  # pulsar manager
  pulsar_manager: false

images:
  proxy:
    repository: apachepulsar/pulsar-all
    # uses defaultPulsarImageTag when unspecified
    tag: 2.8.4
    pullPolicy: IfNotPresent
#  pulsar_manager:
#    repository: apachepulsar/pulsar-manager
#    tag: v0.2.0
#    pullPolicy: IfNotPresent
#    hasCommand: false

kube-prometheus-stack:
  enabled: true
  prometheus:
    enabled: true
    service:
      type: LoadBalancer
  grafana:
#    namespace: grafana
    enabled: true
    adminPassword: 'abcd1234'
    service:
      type: LoadBalancer
  prometheus-node-exporter:
    enabled: true
  alertmanager:
    enabled: false


#prometheus:
#
#  enabled: true
#
#  ## Configuration for Prometheus service
#  ##
#  service:
#    ## Service type
#    ##
#    type: ClusterIP



zookeeper:
  replicaCount: 1
  affinity:
    anti_affinity: false

  volumes:
    persistence: true
    data:
      storageClassName: pulsar-storage

bookkeeper:
  replicaCount: 2
  affinity:
    anti_affinity: false
  volumes:
    persistence: true
    journal:
      storageClassName: pulsar-storage
    ledgers:
      storageClassName: pulsar-storage

broker:
  replicaCount: 2
  affinity:
    anti_affinity: false


proxy:
  replicaCount: 2
  affinity:
    anti_affinity: false




tls:
  enabled: true
  proxy:
    enabled: true
  broker:
    enabled: true
  bookie:
    enabled: true
  zookeeper:
    enabled: true
#tls:
#  enabled: false
#  proxy:
#    enabled: false
#  broker:
#    enabled: false
#  bookie:
#    enabled: false
#  zookeeper:
#    enabled: false

# issue selfsigning certs
certs:
  internal_issuer:
    enabled: true
    type: selfsigning


auth:
  authentication:
    enabled: true
    provider: "jwt"
    jwt:
      # Enable JWT authentication
      # If the token is generated by a secret key, set the usingSecretKey as true.
      # If the token is generated by a private key, set the usingSecretKey as false.
      usingSecretKey: true
  authorization:
    enabled: true
  superUsers:
    # broker to broker communication
    broker: "broker-admin"
    # proxy to broker communication
    proxy: "proxy-admin"
    # pulsar-admin client to broker/proxy communication
    client: "admin"

# instructions for creating secret key and configuring client here: https://pulsar.apache.org/docs/2.10.x/security-jwt/#create-a-secret-key