# apply with kubectl apply -f flow_labs_charts/dev/storage_class.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pulsar-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: xfs
volumeBindingMode: Immediate